apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strapi-app
spec:
  replicas: 1
#  selector:
#     matchLabels:
#        app: strapi-app 
  template:
    metadata:
      labels:
        app: strapi-app
    spec:
      containers:
      - name: strapi-app
        image: strapi/strapi
        ports:
        - containerPort: 1337
        env:
        - name: APP_NAME
          value: "strapi-app"
        - name: DATABASE_CLIENT
          value: "mongo"
        - name: DATABASE_HOST
          value: "mongo-svc"
        - name: DATABASE_PORT
          value: "27017"
        - name: DATABASE_NAME
          value: "strapi"
        - name: DATABASE_USERNAME
          value: ""
        - name: DATABASE_PASSWORD
          value: ""
        - name: DATABASE_SSL
          value: "false"
        - name: DATABASE_AUTHENTICATION_DATABASE
          value: "strapi"
        - name: HOST
          value: "localhost"
#       volumeMounts:
#        - mountPath: /usr/src/api/strapi-app
        
