apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: strapi-ingress
spec:
  rules:
  - host: b.efn.unc.edu.ar
    http:
      paths:
      - backend:
          serviceName: strapi-svc
          servicePort: 80
        path: /
